### PR TITLE
fix: add newline at end-of-file and remove extra empty lines (resolves #33)

### LINKED ISSUE #33: Running `node buildSVG.js` adds extra empty lines to index.html and template.html
## Describe the bug

Running `node buildSVG.js` adds extra empty lines to index.html and template.html which will result in the linting failure.

## To reproduce

1. Run `node buildSVG.js`;
2. Extra empty lines should be added to `index.html` and `src/html/template.html` before `</body>` closing tag;
3. Run `npm run lint`;
4. The linting fails with these errors:

```
Errors returned by lintspaces.newlines:

- index.html:
  (466:-) Expected a newline at the end of the file.
  (466:-) Unexpected additional newlines at the end of the file.

- src/html/template.html:
  (3:-) Expected a newline at the end of the file.
```

## Investigation result

Empty lines are added after this line - https://github.com/inclusive-design/covid-data-monitor/blob/main/buildSVG.js#L34.

### PR DESCRIPTION
**Pull request by klown**
GH-33

### CODE REVIEW

File: buildSVG.js [hunk 1]
```diff
@@ -33,9 +33,10 @@ fluid.removeChildren = function (node) {
 fluid.nodeToText = function (node, indentLevel) {
     var text = node.outerHTML;
     var formatted = jsBeautify.html(text, {
-        indent_level: indentLevel || 0
+        indent_level: indentLevel || 0,
+        end_with_newline: true
     });
-    return formatted;
+    return formatted.replace(/^\s*[\r\n]/gm, ""); // remove empty lines
```
Comment (amb26) [inline buildSVG.js]: This regex will probably not work on Windows. Nosing around StackOverflow I found the following answer which seems plausible and well-approved - https://stackoverflow.com/a/39282395 - could you test it out and see if it is effective at least on your platform?

Comment (klown) [reply buildSVG.js]: The regex used was from another [StackOverflow article](https://stackoverflow.com/questions/16369642/javascript-how-to-use-a-regular-expression-to-remove-blank-lines-from-a-string) -- see "Edit 3" -- which claimed to work on all platforms.  It had the added benefit of not removing the newline at the end of the file, which would cause the lint error this is supposed to fix.

I can't test Windows.  I gather you have and discovered that the regex doesn't work?  I'll try out the other pattern with macOS.

Comment (klown) [reply buildSVG.js]: > I found the following answer which seems plausible and well-approved - https://stackoverflow.com/a/39282395 

That regex isn't right because it removes the last line causing lint to report "Expected a newline at the end of the file"

I've looked around and tried a couple of other regular expressions, and eventually found a page that used a function that should work everywhere -- a sequence of `split("\n"),` `trim()` each array element, discard empty elements, and finally` join("\n")` what's left.

However, `js-beautify` has a configuration property `preserve_newlines` when set that to `false` does what's needed.  The latest code uses that property and forgoes any regex.

**Comment by cindyli** [comment]
@klown, the `js-beautify` config adds an EOF to the end of the file which is great. 

A couple of issues:
1. The config removes all new line characters from `index.html` including desired and undesired ones, which reduce the readability of the file;
2. In `src/html/template.html`, the content after the first new line character is removed, which should not be removed.

**Comment by klown** [comment]
> @klown, the `js-beautify` config adds an EOF to the end of the file which is great.

👍 

> 
> A couple of issues:
> 
>     1. The config removes all new line characters from `index.html` including desired and undesired ones, which reduce the readability of the file;

That's not what I'm seeing.  There are a number of empty lines in `index.html` that are removed by `buildSVG.js`, but I don't see all of the newlines removed.

> 
>     2. In `src/html/template.html`, the content after the first new line character is removed, which should not be removed.

When I first tested the new js-beautify configuration, I noticed that practically all the content of `template.html` was removed.  The only thing left was the first `<div>`.  As a comparison, I checked out the main branch and ran the original `buildSVG.js`.  I got the same result -- all content but the first `<div>` was removed.  I concluded that this was the way it was supposed to work.  What is the expected output here?

I'm baffled as to why we see very different results.

**Comment by cindyli** [comment]
> There are a number of empty lines in `index.html` that are removed by `buildSVG.js`, but I don't see all of the newlines removed.

Yes, the newlines between different html tags are still kept but newlines added by developers for readability are removed.

> As a comparison, I checked out the main branch and ran the original `buildSVG.js`. I got the same result -- all content but the first `<div>` was removed.

You are right, `buildSVG.js` in the main branch produces the same issue. Thanks for discovering it. I've created [a new ticket](https://github.com/inclusive-design/covid-data-monitor/issues/35) for it to be addressed separately.

As discussed in the channel, we'll remove the `preserve_newlines` config and merge this PR so the linting errors after running `buildSVG.js` will be fixed but newlines for readability will still be kept.
